# file name: create-image.yml
name: create-image
on:
  push:
    branches: ['main']
    # tags:
    #   - 'v*'

jobs:
  create-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        id: get-version
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
      - name: login-docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u rahees9983 --password-stdin
      
      - name: checkout
        uses: actions/checkout@v2

      - name: create image
        run: |
          cd app
          docker build -t test-app:${{ steps.get-version.outputs.VERSION }} .
          echo 'Created Image with name:tag = test-app:${{ steps.get-version.outputs.VERSION }}'

      - name: get-images-id
        id: image-id
        run: |
          echo ::set-output name=IMAGE_ID::$(docker images -q test-app:${{ steps.get-version.outputs.VERSION }})

      - name: upload image to registry
        run: |
          docker tag ${{ steps.image-id.outputs.IMAGE_ID }} rahees9983/test-app:${{ steps.get-version.outputs.VERSION }}
          docker push rahees9983/test-app:${{ steps.get-version.outputs.VERSION }}  

      - name: install yq
        uses: mikefarah/yq@v4.15.1 

      - name: update infra yaml file
        run: |
          cd infra
          yq e -i '.spec.template.spec.containers[0].image="rahees9983/test-app:${{ steps.get-version.outputs.VERSION }}"' calc-deployment.yml
          cat calc-deployment.yml

      - name: push change
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.G_TOKEN }}
        with:
          source_file: infra/calc-deployment.yml
          destination_repo: Rahees9983/learn_k8s_with_rahees #PedroLopezITBA/CI-CD-Github-Actions-and-Argo
          destination_branch: main
          destination_folder: infra
          user_email: khanrahees333@gmail.com
          user_name: Rahees9983 #PedroLopezITBA
          commit_message: update image version ${{ steps.get_version.outputs.VERSION }} in yml file
